language: python

addons:
  apt:
    packages:
    - openvpn

branches:
  only: ["master"]

before_install:
  - sudo apt-get update && sudo apt-get install pandoc
  - sudo openvpn path/to/conf.ovpn &>>openvpn-client.log &

script: 
  - make html
  - echo "Done building HTML files"

after_success:
  - echo "Uploading files to `thainlp.org/pythainlp/tutorials`"
  - cd ./build/html
  - find . -type f -name "*" -print -exec curl --ftp-create-dir --ftp-pasv --ipv4 -v -T {} ftp://${FTP_USER}:${FTP_PASSWORD}@thainlp.org/public_html/pythainlp/tutorials/{} \;
  - echo "Done uploading"
  - rm -rf ./build/html
