language: python
env:
  global:
  - 'FTP_USER=[FTP_USER]'
  - 'FTP_PASSWORD=[FTP_PASSWORD]'
  - 'FTP_HOST=[FTP_HOST]'
  - 'FTP_PORT=[FTP_PORT]'

branches:
  only: ["master"]

before_install:
  - sudo apt-get update && sudo apt-get install pandoc

script: 
  - make html
  - echo "Done building HTML files"

after_success:
  - echo "Uploading files to `thainlp.org/pythainlp/tutorials`"
  - find . -type d \( -path "./.*" -o -path "./build/html" \) -prune -o -name "*" -print -exec curl --ftp-create-dirs -T {} ftp://thainlp.org/pythainlp/tutorials/ --user ${FTP_USER}:${FTP_PASSWORD} \;
  - echo "Done uploading"