language: python
env:
  global:
  - 'FTP_USER=[FTP_USER]'
  - 'FTP_PASSWORD=[FTP_PASSWORD]'
  - 'FTP_HOST=[FTP_HOST]'
  - 'FTP_PORT=[FTP_PORT]'

branches:
  only: ["master"]

before_install:
  - sudo apt-get update && sudo apt-get install pandoc

script: 
  - make html
  - echo "Done building HTML files"

after_success:
  - echo "Uploading files to `thainlp.org/pythainlp/tutorials`"
  - cd ./build/html
  - find . -type f -name "*" -print -exec curl  -T {} ftp://${FTP_HOST}:${FTP_PORT}/public_html/pythainlp/tutorials/{} --user ${FTP_USER}:${FTP_PASSWORD} --ftp-create-dir --ipv4 --ftp-ssl --disable-epsv --ftp-pasv \;
  - echo "Done uploading"
  - rm -rf ./build/html
