image: ubuntu

install:
  - sudo apt-get update && sudo apt-get install -y pandoc
  - pip install -r requirements.txt
build_script: 
  - make html
  - echo "Done building HTML files"

after_build:
  - echo "Done"
