image: ubuntu1604

install:
  - sudo apt-get update && sudo apt-get install -y pandoc python3
  - sudo apt-get install -y python3-sphinx
  - sudo pip install -r requirements.txt

build_script: 
  - sudo make html
  - echo "Done building HTML files"

after_build:
  - echo "Start uploading files to `thainlp.org/pythainlp.tutorials` via FTP"
  - cd ./build/html
  - find . -type f -name "*" -print -exec curl --ftp-create-dir --ipv4 -T {} ftp://${FTP_USER}:${FTP_PASSWORD}@thainlp.org/public_html/pythainlp/tutorials/{} \;
  - echo "Done uploading"
  - rm -rf ./build/html
