image: ubuntu1604

branches:
  only:
    - master

skip_commits:
  message: /\(skip ci\)/     # Skip a new build if message contains '(skip ci)'

# scripts that run after cloning repository
install:
  - sudo add-apt-repository ppa:jonathonf/python-3.6 -y
  - sudo apt-get update
  - sudo apt install -y python3.6 
  - sudo apt install -y python3.6-dev
  - sudo apt install -y python3.6-venv
  - wget https://bootstrap.pypa.io/get-pip.py
  - sudo python3.6 get-pip.py
  - sudo ln -s /usr/bin/python3.6 /usr/local/bin/python
  - sudo apt-get install -y pandoc libicu-dev
  - sudo pip install -r requirements.txt

build_script: 
  - sudo make html
  - echo "Done building HTML files"
  - echo "Start cleaning the directory /tutorials"
  - sudo bash ./clean_directory.sh $FTP_USER $FTP_PASSWORD 
  - echo "Uploading files to `thainlp.org/pythainlp/tutorials`"
  - cd ./build/html
  - find . -type f -name "*" -print -exec curl --ftp-create-dir --ipv4 -T {} ftp://${FTP_USER}:${FTP_PASSWORD}@thainlp.org/public_html/pythainlp/tutorials/{} \;
  - echo "Done uploading"
  - echo "Done uploading files to /tutorials"

artifacts:
  - path: ./build/html
    name: document

after_build:
  - echo "Done build and deploy"
  - appveyor exit

test: off